# Get common recipes
recipes = ENV['CMSSW_BASE'] + '/src/FinalStateAnalysis/PlotTools/rake/recipes.rake'
import recipes
require ENV['CMSSW_BASE'] + '/src/FinalStateAnalysis/PlotTools/rake/tools.rb'

$jobid = ENV['jobid']
$blind = ENV['blind']

# Figure out what run period we are in
$period = '8TeV'
if $jobid.include? '7TeV'
  $period = '7TeV'
end

check_luminosity(['data_DoubleElectron', 'data_DoubleMu', 'data_MuEG'], $period, $jobid)

task :getlumi, [:sample] do |t, args|
  puts get_lumi(args.sample, $jobid)
end

################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt")
  inputs = inputs.select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end

#puts get_sample_names('data_DoubleMu')

samples = Hash[
  "ewk" => Array['Zjets_M50', 'WplusJets_madgraph', 'TTplusJets_madgraph'] + get_sample_names('WZ') + get_sample_names('WWJet')+ get_sample_names('ZZ'),     #'ZZJetsTo4L_pythia',
  "wjets" => Array['WplusJets_madgraph'],
  "zjets" => Array['Zjets_M50'],
  "diboson" => get_sample_names('ZZ')+get_sample_names('WZ') + get_sample_names('WWJet'),
  "signal" => get_sample_names('VH') + get_sample_names('WH'),
  # Automagically figure out what data samples we have
  "data_m" =>  get_sample_names("data_SingleMu"),
  "data_mm" =>  get_sample_names("data_DoubleMu"),
  "data_em" => get_sample_names("data_MuEG"),
  "data_ee" => get_sample_names("data_DoubleElectron"),
]

# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end

file "baseSelections.py" => "electronids.py" do |t|
  sh "touch #{t.name}"
end

file "optimizer.py" => "baseSelections.py" do |t|
  sh "touch #{t.name}"
end

################################################################################
## Recipes to measure fake rates 
##  targets:
##     fakerates - measure all fakerates
################################################################################

# Map which samples need to be analyzed by which analyzer
fr_analyzer_sample_map = Hash[
  "FakeRatesEE.py"  => samples['data_ee'] + samples['diboson'],
  "ChargeFlipProbabilityEE.py" => samples['zjets'],
  "FakeRatesEM.py"  => samples['diboson'] + samples['data_em'],
  "FakeRatesMM.py"  => samples['diboson'] + samples['data_mm'],
  "FakeRatesMMT.py" => samples['diboson'] + samples['data_mm'],
#  "FakeRatesEMT.py" => samples['diboson'] + samples['data_em'],
#  "FakeRatesMMM.py" => samples['diboson'] + samples['data_mm'],
]

fr_analyzer_dep_map = Hash[
  "ChargeFlipProbabilityEE.py" => Array["baseSelections.py"], 
  "FakeRatesEE.py"  => Array["baseSelections.py"],
  "FakeRatesEM.py"  => Array["baseSelections.py"],
  "FakeRatesMM.py"  => Array["baseSelections.py"],
  "FakeRatesMMT.py" => Array["baseSelections.py"],
#  "FakeRatesEMT.py" => Array["baseSelections.py"],
#  "FakeRatesMMM.py" => Array["baseSelections.py"],
]

# Create an empty placeholder to enable tab-completion
task :fakerates => []
#check if base class or some selections has changed
fr_analyzer_sample_map.each do |analyzer, the_samples|
  file analyzer => fr_analyzer_dep_map[analyzer] do |t|
    sh "touch #{t.name}"
  end
end

# Create tasks for each sample + analyzer
fr_analyzer_sample_map.each do |analyzer, the_samples|
  results = Array[]
  get_analyzer_results(analyzer, the_samples).each do |result|
    results << result
  end
  task :fakerates => results do |t|
  end
  #end
end

################################################################################
## Recipes to fit fake rates
##  targets:
##     fits
################################################################################
# Output directory
$frfit_dir = "results/#{$jobid}/fakerate_fits"
directory $frfit_dir

# Common fit functions
$exponential = "scale*TMath::Exp(x*decay)+offset"
$exponential_vars =  "scale[0.5, 0, 5],decay[-1e-2, -1, -1e-4],offset[1e-2, 0, 0.5]"

$landau = "scale*TMath::Landau(x,mu,sigma,0)+offset"
$landau_vars =  "scale[0.5, 0, 15],mu[5, 0, 30],sigma[1.9, 0.1, 20],offset[1e-2, 0, 0.5]"

$flat = "offset"
$flat_vars =  "offset[1e-2, 0, 0.5]"

$fr_binning =  "10,12,15,20,25,30,40,50,70,100"
$fr_binning_tight =  "10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,45,50,60,65,70,80,100"

def make_landau(chan, datas)
  return Hash[
              "samples" => Array["diboson", "data_#{datas.downcase}"],
              "analyzer" => "FakeRates#{chan.upcase}",
              "function" => $landau,
              "variables" => $landau_vars,
              "rebin" => $fr_binning,
              "range" => "10 100",
              'fitter' => 'fit_efficiency_chi2.py',
             ]
end

def make_exponential(chan, datas)
  return Hash[
              "samples" => Array["diboson", "data_#{datas.downcase}"],
              "analyzer" => "FakeRates#{chan.upcase}",
              "function" => $exponential,
              "variables" => $exponential_vars,
              "rebin" => $fr_binning,
              "range" => "10 100",
              'fitter' => 'fit_efficiency_chi2.py',
             ]
end

def make_cruijff(chan, datas)
  return Hash[
              "samples" => Array["diboson", "data_#{datas.downcase}"],
              "analyzer" => "FakeRates#{chan.upcase}",
              "function" => $landau,
              "variables" => $landau_vars,
              "rebin" => $fr_binning,
              "range" => "10 100",
              'fitter' => 'fit_efficiency_chi2.py',
             ]
end

def make_constant(chan, datas)
  return Hash[
              "samples" => Array["diboson", "data_#{datas.downcase}"],
              "analyzer" => "FakeRates#{chan.upcase}",
              "function" => $landau,
              "variables" => $landau_vars,
              "rebin" => $fr_binning,
              "range" => "10 100",
              'fitter' => 'fit_efficiency_chi2.py',
             ]
end

def make_kNN(chan, datas)
  return Hash[
              "samples" => Array["diboson", "data_#{datas.downcase}"],
              "analyzer" => "FakeRates#{chan.upcase}",
              'fitter' => 'train_kNN.py',
             ]
end

iso_points   = ['idiso02', 'h2taucuts', 'h2taucuts020']
electronIds  = ['eid12Loose', 'eid12Medium', 'eid12Tight'] #, 'eid13Loose', 'eid13Tight']
elewps       = electronIds.product(iso_points)
elewps       = elewps.map{|x,y| "#{x}_#{y}"}
pt_regions   = ['pt10', 'pt20']
muonwps      = ['h2taucuts', 'h2taucuts020', 'pfidiso02']
fr_fits      = Hash.new
kNN_trains   = Hash.new
muon_kNN_vars= ['muonJetPt', 'muonPt', 'muonJetCSVBtag'] #'muonPVDXY']
electron_kNN_vars= ['electronJetPt', 'electronPt']


#############
#  EM datas
#############
emcrs = ['qcd', 'wjets']
elewps.each do |ele_wp|
  emcrs.each do |cr|
    pt_regions.each do |ptr|
      key = "e_#{cr}_#{ptr}_#{ele_wp}_eJetPt"
      #fr_fits[key] =  make_exponential('em', 'em') #fit EVERYTHING with exponential, in case change afterwards

      key = "e_#{cr}_#{ptr}_#{ele_wp}_electronInfo"
      kNN_trains[key] =  make_kNN('em', 'em') 
      kNN_trains[key]['vars'] = electron_kNN_vars
    end
  end
end

#muon fakes from em
#mmcrs = ['qcd', 'wjets']
#muonwps.each do |mu_wp|
#  mmcrs.each do |cr|
#    pt_regions.each do |ptr|
#      key = "m_M#{cr}_#{ptr}_#{mu_wp}_muonInfo"
#      kNN_trains[key] =  make_kNN('em', 'em') 
#      kNN_trains[key]['vars'] = muon_kNN_vars
#    end
#  end
#end


#############
#  EE datas
#############
eecrs = ['qcd', 'wjetsNoZmass']
elewps.each do |ele_wp|
  eecrs.each do |cr|
    key = "ee_#{cr}_pt10_#{ele_wp}_electronJetPt"
    #fr_fits[key] =  make_landau('ee', 'ee') #fit pt10 with landau
    key = "ee_#{cr}_pt20_#{ele_wp}_electronJetPt"
    #fr_fits[key] =  make_exponential('ee', 'ee') #fit pt20 with expo

    key = "ee_#{cr}_pt10_#{ele_wp}_electronInfo"
    kNN_trains[key] =  make_kNN('ee', 'ee')
    kNN_trains[key]['vars'] = electron_kNN_vars
    key = "ee_#{cr}_pt20_#{ele_wp}_electronInfo"
    kNN_trains[key] =  make_kNN('ee', 'ee')
    kNN_trains[key]['vars'] = electron_kNN_vars
  end
end
#fr_fits["ee_wjetsNoZmass_pt10_eid12Medium_h2taucuts020_electronJetPt"] = make_constant('ee', 'ee')

#############
#  MM datas
#############
mmcrs = ['qcd', 'wjets']
muonwps.each do |mu_wp|
  mmcrs.each do |cr|
    pt_regions.each do |ptr|
      key = "m_#{cr}_#{ptr}_#{mu_wp}_muonJetPt"
      #fr_fits[key] =  make_landau('mm', 'mm')

      key = "m_#{cr}_#{ptr}_#{mu_wp}_muonInfo"
      kNN_trains[key] =  make_kNN('mm', 'mm')
      kNN_trains[key]['vars'] = muon_kNN_vars
    end
  end
end
#fr_fits["m_qcd_pt20_h2taucuts_muonJetPt"] = make_cruijff('mm', 'mm')
#fr_fits["m_qcd_pt20_h2taucuts020_muonJetPt"] = make_cruijff('mm', 'mm')


#Tau stuff (by hand, they are just 2)
fr_fits["t_ztt_pt20_mvaloose_tauPt"] = Hash[
    "samples" => Array["diboson", "data_mm"],
    "analyzer" => "FakeRatesMMT",
    "function" => $exponential,
    "variables" => $exponential_vars,
    "rebin" => 5,
    "range" => "20 100",
  ]

fr_fits["t_ztt_pt20_hpsloose_tauPt"] = Hash[
    "samples" => Array["diboson", "data_mm"],
    "analyzer" => "FakeRatesMMT",
    "function" => $exponential,
    "variables" => $exponential_vars,
    "rebin" => 5,
    "range" => "20 100",
  ]

# Placeholder
task :fits => []
task :kNN  => []

################################################
# Create tasks for all the fr_fits
################################################
fr_fits.each do |fit, fit_info|
  fit_configuration = fit.split("_")
  region = ''
  denom  = ''
  num    = ''
  var    = ''

  if fit_configuration.size() == 6 #check if we have an idIso with _ separation
    region = fit_configuration[1]
    denom  = fit_configuration[2]
    num = "#{fit_configuration[3]}_#{fit_configuration[4]}"
    var = fit_configuration[5]
  else #otherwise as usual
    region = fit_configuration[1]
    denom  = fit_configuration[2]
    num = fit_configuration[3]
    var = fit_configuration[4]
  end

  # Expand sample list
  subsample_inputs = []
  fit_info['samples'].each do |sample|
    subsample_inputs += samples[sample]
  end

  fit_output = $frfit_dir + "/#{fit}.root"
  subsamples_inputs_result_list = subsample_inputs.map{|x|  "results/#{$jobid}/#{fit_info['analyzer']}/#{x}.root"}
  subsample_input_list = subsamples_inputs_result_list.join(" ")

  # Path to histograms in root files
  denom_path = Array[region, denom, var].join("/")
  num_path = Array[region, denom, num, var].join("/")

  # Correct the numerator and denominator for WZ + ZZ contamination
  # The output is stored in "numerator" and "denominator"
  corrected_file = fit_output.sub('.root', '.corrected_inputs.root')
  file corrected_file => subsamples_inputs_result_list + [fit_info['analyzer'] + '.py', "CorrectFakeRateData.py"] do |t|
    sh "mkdir -p #{$frfit_dir}"
    sh "python CorrectFakeRateData.py --files #{subsample_input_list} --lumifiles inputs/#{$jobid}/*sum --outputfile #{t.name} --numerator '#{num_path}' --denom '#{denom_path}' --rebin #{fit_info['rebin']}"
    puts ""
  end

  file fit_output => corrected_file do |t|
    sh "fit_efficiency_chi2.py #{fit_output} numerator denominator \'#{fit_info['function']}\' \'#{fit_info['variables']}\' #{corrected_file} --plot --xrange #{fit_info['range']} --xtitle 'Jet Pt (GeV)'"
    puts ""
  end
  task :fits => fit_output

end


################################################
#create tasks for running kNN
################################################
kNN_files = Array[]
kNN_trains.each do |kNN, info|
  kNN_configuration = kNN.split("_")
  region = ''
  denom  = ''
  cut    = ''
  var    = ''

  if kNN_configuration.size() == 6 #check if we have an idIso with _ separation
    region = kNN_configuration[1]
    denom = kNN_configuration[2]
    cut = "#{kNN_configuration[3]}_#{kNN_configuration[4]}"
    var = kNN_configuration[5]
  else #otherwise as usual
    region = kNN_configuration[1]
    denom = kNN_configuration[2]
    cut = kNN_configuration[3]
    var = kNN_configuration[4]
  end

  knn_output = $frfit_dir + "/#{kNN}.kNN.root"

  # Expand sample list
  subsample_inputs = []
  info['samples'].each do |sample|
    subsample_inputs += samples[sample]
  end
  subsamples_inputs_result_list = subsample_inputs.map{|x|  "results/#{$jobid}/#{info['analyzer']}/#{x}.root"}
  subsample_input_list = subsamples_inputs_result_list.join(" ")

  # Path to tree in root files
  tree_path = Array[region, denom, var].join("/")
  vars_str  = info['vars'].join(" ")

  file knn_output => subsamples_inputs_result_list + [info['analyzer'] + '.py',] do |t|
    sh "mkdir -p #{$frfit_dir}"
    sh "train_kNN.py --files #{subsample_input_list} --outputfile #{knn_output} --tree #{tree_path} --cut #{cut} --variables #{vars_str} --makePlots 0"
  end
  task :kNN => knn_output
  kNN_files << knn_output
end

#Rake.application.tasks.each do |t|
#  puts "#{t}, #{t.prerequisites}"
#end

################################################
#charge fake rate tasks
################################################
task :charge_fakes => []
elewps.each do |iso_label|
  output = "#{$frfit_dir}/charge_flip_prob_map_#{iso_label}.root"
  file output => ["results/#{$jobid}/ChargeFlipProbabilityEE/#{samples["zjets"][0]}.root", "make_charge_flip_probalility_map.py"] do |t|
    sh "python make_charge_flip_probalility_map.py #{t.name} #{iso_label}/flipped_electrons #{iso_label}/matched_electrons #{t.prerequisites[0]}"
  end
  task :charge_fakes => output
end

task :fits => :charge_fakes

################################################################################
## Recipes to analyze WH
##  targets:
##     mmt
##     emt
##     mmcontrol
##     emcontrol
##     eecontrol
################################################################################
fake_rate_files = fr_fits.keys.map{|x| "#{$frfit_dir}/#{x}.root"}

# IF the FR fits change, make sure we re-run the analyses
file "WHAnalyzeEMT.py" => kNN_files.select{|x| x.start_with?("#{$frfit_dir}/e_")} + \
               kNN_files.select{|x| x.start_with?("#{$frfit_dir}/m_")} + \
               fake_rate_files.select{|x| x.start_with?("#{$frfit_dir}/t_")} + \
               Array["optimizer.py",
                     'WHAnalyzerBase.py',
                     "fakerate_functions.py",
                     "mcCorrectors.py"] do |t|
  sh "touch #{t.name}"
end

file "WHAnalyzeMMT.py" => kNN_files.select{|x| x.start_with?("#{$frfit_dir}/m_")} + \
               fake_rate_files.select{|x| x.start_with?("#{$frfit_dir}/t_")} + \
               ["optimizer.py",
                'WHAnalyzerBase.py',
                "fakerate_functions.py",
                "mcCorrectors.py"] do |t|
  sh "touch #{t.name}"
end

file "WHAnalyzeEET.py" => kNN_files.select{|x| x.start_with?( "#{$frfit_dir}/ee_")} + \
               fake_rate_files.select{|x| x.start_with?("#{$frfit_dir}/t_")} + \
               ["optimizer.py",
                'WHAnalyzerBase.py',
                "fakerate_functions.py",
                "mcCorrectors.py",
                "chargeflipcuts.py"] do |t|
  sh "touch #{t.name}"
end

mmt_results = get_analyzer_results("WHAnalyzeMMT.py", samples['ewk'] + samples['data_mm'] + samples['signal'])
emt_results = get_analyzer_results("WHAnalyzeEMT.py", samples['ewk'] + samples['data_em'] + samples['signal'])
eet_results = get_analyzer_results("WHAnalyzeEET.py", samples['ewk'] + samples['data_ee'] + samples['signal'])

mmt_debug   = get_analyzer_results("WHAnalyzeMMT.py", Array['Zjets_M50'] )
task :mmt_dbg => mmt_debug
eet_data    = get_analyzer_results("WHAnalyzeEET.py", samples['data_ee'])
task :eet_data => eet_data + fake_rate_files.select{|x| x.start_with?( 'ee_')}

task :mmt => mmt_results
task :emt => emt_results
task :eet => eet_results

task :mmcontrol => get_analyzer_results("ControlZMM.py", samples['ewk'] + samples['data_mm'])
task :emcontrol => get_analyzer_results("ControlEM.py", samples['ewk'] + samples['data_em'])
task :eecontrol => get_analyzer_results("ControlZEE.py", samples['data_ee'] + samples["zjets"]) + Dir.glob("#{$frfit_dir}/ee*h2taucuts_electronJetPt.root") #samples['ewk'] +

task :mmt_signal => get_analyzer_results("WHAnalyzeMMT.py", samples['signal'])
task :emt_signal => get_analyzer_results("WHAnalyzeEMT.py", samples['signal'])
task :eet_signal => get_analyzer_results("WHAnalyzeEET.py", samples['signal'])
task :run_signal => [
   :mmt_signal,
   :emt_signal,
   :eet_signal]

task :mmt_signal120 => get_analyzer_results("WHAnalyzeMMT.py", samples['signal'].select{|x| x.include? "120"})
task :emt_signal120 => get_analyzer_results("WHAnalyzeEMT.py", samples['signal'].select{|x| x.include? "120"})
task :eet_signal120 => get_analyzer_results("WHAnalyzeEET.py", samples['signal'].select{|x| x.include? "120"})
task :run_signal120 => [
   :mmt_signal120,
   :emt_signal120,
   :eet_signal120]

################################################################################
# Recipes to make control plots
#  targets:
#      plot_zmm
#      plot_zee
#      plot_em
################################################################################

# Output directories

$zmmdir = "results/#{$jobid}/plots/zmm/"
directory $zmmdir

file "#{$zmmdir}/.plot_timestamp" => Array["PlotControlZMM.py"]+get_analyzer_results("ControlZMM.py", samples['ewk'] + samples['data_mm']) do |t|
  sh "python PlotControlZMM.py"
  sh "touch #{t.name}"
end
task :plot_zmm => "#{$zmmdir}/.plot_timestamp"

$emdir  = "results/#{$jobid}/plots/em/"
directory $emdir 

file "#{$emdir}/.plot_timestamp" => Array["PlotControlZMM.py"]+get_analyzer_results("ControlZMM.py", samples['ewk'] + samples['data_mm']) do |t|
  sh "python PlotControlEM.py"
  sh "touch #{t.name}"
end
task :plot_em  => "#{$emdir}/.plot_timestamp"

$zeedir = "results/#{$jobid}/plots/zee/"
directory $zeedir

file "#{$zeedir}/.plot_timestamp" => Array["PlotControlZEE.py"]+get_analyzer_results("ControlZEE.py", samples['data_ee']) do |t|
  t.investigation
  sh "python PlotControlZEE.py"
  sh "touch #{t.name}"
end
task :plot_zee => "#{$zeedir}/.plot_timestamp"

################################################################################
# Recipes to make signal plots
#  targets:
#      plot_mmt
#      plot_eet
#      plot_emt
################################################################################
# Output directories
$mmtdir = "results/#{$jobid}/plots/mmt/"
$emtdir = "results/#{$jobid}/plots/emt/"
$eetdir = "results/#{$jobid}/plots/eet/"

directory $mmtdir
directory $eetdir
directory $emtdir

# The .root files with the shapes
file "#{$mmtdir}/mmt_shapes_#{$period}.root" => ['WHPlotterMMT.py', 'WHPlotterBase.py'] do |t|
  sh "python WHPlotterMMT.py"
end
task :plot_mmt => "#{$mmtdir}/mmt_shapes_#{$period}.root"

file "#{$emtdir}/emt_shapes_#{$period}.root" => ['WHPlotterEMT.py', 'WHPlotterBase.py'] do |t|
  sh "python WHPlotterEMT.py"
end
task :plot_emt => "#{$emtdir}/emt_shapes_#{$period}.root"

file "#{$eetdir}/eet_shapes_#{$period}.root" => ['WHPlotterEET.py', 'WHPlotterBase.py'] do |t|
  sh "python WHPlotterEET.py"
end
task :plot_eet => "#{$eetdir}/eet_shapes_#{$period}.root"

################################################################################
# Recipes to make data cards (plots come for free)
#  targets:
#      mmt_shapes
#      emt_shapes
#      eet_shapes
#      cards
#      copycards -> move cards to official HTT CVS area
################################################################################

#categories
$categories_map = Hash[
   'eet' => File.open("card_config/cgs.conf.eet.#{$period}").select {|x| x.start_with? 'categories'}[0].split(':')[1].split(',').map{|x| x.strip},
   'emt' => File.open("card_config/cgs.conf.emt.#{$period}").select {|x| x.start_with? 'categories'}[0].split(':')[1].split(',').map{|x| x.strip},
   'mmt' => File.open("card_config/cgs.conf.mmt.#{$period}").select {|x| x.start_with? 'categories'}[0].split(':')[1].split(',').map{|x| x.strip},
]

# Recipes for adding stat. error shapes.  Makes a new file task:
# input_file_stat_errors.root => input_file.root
def add_fake_errors(input_file, channel, prefix)
  output_file =  "#{File.dirname(input_file)}/#{channel}_shapes_#{prefix}_statshapes.root"
  output_sys_list = output_file.sub('.root', ".txt")
  file output_file => [input_file] do |t|
    sh "add_stat_shapes.py #{input_file} #{output_file} --filter '#{prefix}/fakes' --prefix CMS_vhtt_#{$period}_#{prefix}_fakeshape > #{output_sys_list}"
  end
  return output_file
end

mmt_shape_file = "#{$mmtdir}/mmt_shapes_#{$period}.root"
$categories_map['mmt'].each do |category|
  mmt_shape_file = add_fake_errors(mmt_shape_file, "mmt", category)
end
task :mmt_shapes => mmt_shape_file

emt_shape_file = "#{$emtdir}/emt_shapes_#{$period}.root"
$categories_map['emt'].each do |category|
  emt_shape_file = add_fake_errors(emt_shape_file, "emt", category)
end
task :emt_shapes => emt_shape_file

eet_shape_file = "#{$eetdir}/eet_shapes_#{$period}.root"
$categories_map['eet'].each do |category|
  eet_shape_file = add_fake_errors(eet_shape_file, "eet", category)
end
task :eet_shapes => eet_shape_file

$carddir = "results/#{$jobid}/cards"

cardmasses = get_sample_names('VH') #get all the VH samples available
cardmasses = cardmasses.select{|x| x.include? "H2Tau"} #get only the H2Tau, to avid repetition
cardmasses = cardmasses.map{|x| x.sub("VH_H2Tau_M-","")} #remove trailing name, the leftover is the mass (as a string)
cardmasses = cardmasses.map{|x| Integer(x)} #maps to integers (don't know if it's really needed but can't harm)
cardmasses = cardmasses.select{|x| x <= 140} #FIXME! to be removed!
#puts cardmasses

$to_extrapolate = cardmasses.select{|x| x > 140}

def make_morphing_task(channel, shapefile)
  ret = "#{$carddir}/#{channel}/shapes.root"
  file ret => [shapefile] do |t|
    sh "mkdir -p `dirname #{t.name}`"
    sh "cp #{t.prerequisites[0]} #{t.name}"
    sh "horizontal-morphing.py --categories='#{$categories_map[channel].join(',')}' --samples='WH_hww{MASS}' --uncerts='' --masses='110,120,130,140' --step-size=5 -i #{t.name}"# --extrapolate=#{$to_extrapolate.join(",")} #{t.name}" #FIXME! to be removed!
  end
  return ret
end

mmt_morphed_shape_file = make_morphing_task('mmt', mmt_shape_file)
task :mmt_morphed_shapes => mmt_morphed_shape_file

emt_morphed_shape_file = make_morphing_task('emt', emt_shape_file)
task :emt_morphed_shapes => emt_morphed_shape_file

eet_morphed_shape_file = make_morphing_task('eet', eet_shape_file)
task :eet_morphed_shapes => eet_morphed_shape_file


def make_cgs_conf_task(channel)
  ret = "#{$carddir}/#{channel}/cgs.conf"
  file ret => ["card_config/cgs.conf.#{channel}.#{$period}"] do |t|
    carddir_channel = File.dirname(t.name)
    sh "mkdir -p #{carddir_channel}"
    sh "cp #{t.prerequisites[0]} #{t.name}"
  end
  return ret
end

def make_unc_conf_task(channel, opttag='')
  ret = "#{$carddir}/#{channel}/unc.conf" 
  file ret => ["card_config/unc.conf.#{channel}.#{$period}"] + Dir.glob("results/#{$jobid}/plots/#{channel}/#{channel}#{opttag}_shapes_*_statshapes.root") do |t|
    # Copy the basic template
    carddir_channel = File.dirname(t.name)
    sh "mkdir -p #{carddir_channel}"
    sh "cp #{t.prerequisites[0]} #{t.name}"
    # Append all the stat shape types
    sh "echo '' >> #{t.name}"
    sh "echo '# Stat shape uncertainties' >> #{t.name}"
    Dir.glob("results/#{$jobid}/plots/#{channel}/#{channel}#{opttag}_shapes_*_statshapes.txt").each do |list|
      sh "cat #{list} | xargs -n 1 -I {} echo '{} shape' >> #{t.name}"
    end
  end
  return ret
end

def make_unc_vals_task(channel, opttag='')
  ret = "#{$carddir}/#{channel}/unc.vals"
  file ret => ["card_config/unc.vals.#{channel}.#{$period}", 
    "#{$carddir}/#{channel}/shapes.root"]  do |t| #+ Dir.glob("results/#{$jobid}/plots/#{channel}/*_statshapes.root") shapes.root depends on statshapes, so are redundant
    # Copy the basic template
    carddir_channel = File.dirname(t.name)
    sh "mkdir -p #{carddir_channel}"
    sh "cp #{t.prerequisites[0]} #{t.name}"
    # Append all the stat shape types
    sh "echo '' >> #{t.name}"
    sh "echo '# Stat shape uncertainties' >> #{t.name}"
    Dir.glob("results/#{$jobid}/plots/#{channel}/#{channel}#{opttag}_shapes_*_statshapes.txt").each do |list|
      category = list.split('/')[-1].split('_')[-2]
      sh "cat #{list} | xargs -n 1 -I {} echo '#{category} fakes {} 1.0' >> #{t.name}"
    end
    sh "python get_fake_systematic.py #{carddir_channel}/shapes.root #{$categories_map[channel].join(',')} CMS_vhtt_#{channel}_fakes_#{$period} >> #{t.name}"
  end
end

def make_datacard_task(mass, channel)
  card = "#{$carddir}/#{channel}/#{mass}/vhtt_#{channel}.txt"  
  carddir = $carddir #makes a copy so that if $cardir changes this does not
  file card => ["#{$carddir}/#{channel}/shapes.root",
                "#{$carddir}/#{channel}/unc.conf", 
                "#{$carddir}/#{channel}/unc.vals", 
                "#{$carddir}/#{channel}/cgs.conf"] do |t|
    sh "mkdir -p #{carddir}"
    chdir(carddir) do
      sh "mkdir -p #{channel}/#{mass}"
      # Link the shape file in the card directory so combine can run from anywhere
      chdir("#{channel}/#{mass}") do
        sh "rm -f shapes.root"
        sh "ln -s ../shapes.root"
      end
      chdir("#{channel}") do
        sh "create-datacard.py -i shapes.root -o #{mass}/vhtt_#{channel}.txt #{mass} --categories '#{$categories_map[channel].join(',')}'"
      end
    end
  end
  return card
end

def combine_channels(mass)
  #makes copy-paste easier
  channel = 'llt'
  card = "#{$carddir}/#{channel}/#{mass}/vhtt_#{channel}.txt"
  carddir = $carddir #makes a copy so that if $cardir changes this does not
  file card => ["#{$carddir}/mmt/#{mass}/vhtt_mmt.txt",
                "#{$carddir}/emt/#{mass}/vhtt_emt.txt",
                "#{$carddir}/eet/#{mass}/vhtt_eet.txt"] do |t|
    sh "mkdir -p #{carddir}/#{channel}/#{mass}"
    sh "hadd  -f #{carddir}/#{channel}/shapes.root #{carddir}/?mt/shapes.root  #{carddir}/eet/shapes.root "
    chdir("#{carddir}/#{channel}/#{mass}") do
      sh "rm -f shapes.root"
      sh "ln -s ../shapes.root"
      local_paths = t.prerequisites.map{|x| x.sub(carddir,'../..')}
      sh "combine_cards_with_names.sh #{ local_paths.join(' ')} > vhtt_#{channel}.txt"
    end
  end
  return card
end

def make_timestamp_task(cardmasses, channel)
  timestamp = "#{$carddir}/#{channel}/.creation_timestamp"
  #creates the tasks
  make_unc_conf_task(channel)
  make_unc_vals_task(channel)
  make_cgs_conf_task(channel)
  file timestamp => cardmasses.map{|x| make_datacard_task(x, channel)} do |t|
    sh "touch #{t.name}"
  end
end

file "#{$carddir}/llt/.creation_timestamp" => cardmasses.map{|x| combine_channels(x)} do |t|
  sh "touch #{t.name}"
end

task :cards => [make_timestamp_task(cardmasses, 'mmt'),
                make_timestamp_task(cardmasses, 'emt'),
                make_timestamp_task(cardmasses, 'eet'),
                "#{$carddir}/llt/.creation_timestamp"
               ]

## cardmasses.each do |mass|
##   task :cards => make_datacard_task(mass, 'mmt')
##   task :cards => make_datacard_task(mass, 'emt')
##   task :cards => make_datacard_task(mass, 'eet')
##   task :cards => combine_channels(mass)
##   #task :cards => make_datacard_task(mass, 'llt', '')
## end

################################################################################
# Recipes to make limits
#  targets:
#      limit_mmt
#      limit_emt
#      limit_eet
#      limit_llt
#      limits
################################################################################

def make_limit_task(channel)
  limit_timestamp = "#{$carddir}/#{channel}/.limits_computed"
  carddir = $carddir #makes a copy so that if $cardir changes this does not
  file limit_timestamp => "#{$carddir}/#{channel}/.creation_timestamp" do |t|
    chdir("#{carddir}/#{channel}") do
      sh "ls -d [0-9]* | xargs -n 1 -P 10 -I {} compute_significance.sh {} #{$blind}"
    end
    sh "compute_limits.sh #{carddir}/#{channel} 10 #{$blind}"
  end
  return limit_timestamp
end

task :limit_mmt => make_limit_task('mmt')
task :limit_emt => make_limit_task('emt')
task :limit_eet => make_limit_task('eet')
task :limit_llt => make_limit_task('llt')
task :limits => Array[:limit_mmt,
                      :limit_emt,
                      :limit_eet,
                      :limit_llt]

################################################################################
# Recipes to harvest limits
#  targets:
#          harvest_limit_mmt
#          harvest_limit_emt
#          harvest_limit_eet
#          harvest_limit_llt
#          harvest_limits
################################################################################


def make_json_limit_task(channel)
  samples_map = Hash['mmt' => 'data_DoubleMu', 
                     'eet' => 'data_DoubleElectron', 
                     'emt' => 'data_MuEG',
                     'llt' => 'data_DoubleMu',
                    ]
  carddir = $carddir #makes a copy so that if $cardir changes this does not
  json_stamp = "#{$carddir}/#{channel}/.limit_harvested"
  file json_stamp => "#{$carddir}/#{channel}/.limits_computed" do |t|
    sh "harvest_limits.py #{carddir}/#{channel}"
    sh "touch #{t.name}"
    sh "add_tag_to_json.py #{carddir}/#{channel}/*.json -l jobid -t #{$jobid}"
    sh "add_tag_to_json.py #{carddir}/#{channel}/*.json -l lumi -t #{get_lumi(samples_map[channel], $jobid)}"
  end
  return json_stamp
end

task :harvest_limit_mmt => make_json_limit_task('mmt')
task :harvest_limit_emt => make_json_limit_task('emt')
task :harvest_limit_eet => make_json_limit_task('eet')
task :harvest_limit_llt => make_json_limit_task('llt')
task :harvest_limits => Array[:harvest_limit_mmt,
                              :harvest_limit_emt,
                              :harvest_limit_eet,
                              :harvest_limit_llt]

################################################################################
# Recipes to harvest limits (for debugging/internal use)
#  targets:
#          plot_limit_mmt
#          plot_limit_emt
#          plot_limit_eet
#          plot_limit_llt
#          compare_limits
#          plot_limits
################################################################################
$limitdir = "results/#{$jobid}/plots/limits/"

def make_plot_limit_task(channel)
  filename   = "#{$limitdir}/#{channel}_limit"
  limit_plot = "#{filename}.png"
  carddir = $carddir #makes a copy so that if $cardir changes this does not
  file limit_plot => "#{$carddir}/#{channel}/.limit_harvested" do |t|
    sh "mkdir -p #{$limitdir}"
    sh "plot_limit.py #{carddir}/#{channel}/*.json -o #{filename} --legend-on-the-left --xrange=[110,140]"
  end
  return limit_plot
end

task :plot_limit_mmt => make_plot_limit_task('mmt')
task :plot_limit_emt => make_plot_limit_task('emt')
task :plot_limit_eet => make_plot_limit_task('eet')
task :plot_limit_llt => make_plot_limit_task('llt')
task :plot_limits => Array[:plot_limit_mmt,
                           :plot_limit_emt,
                           :plot_limit_eet,
                           :plot_limit_llt]
task :compare_limits => :plot_limits do |t|
  puts 'non available for the moment'
  #sh "compare_limit.py #{$carddir}/???/*expected*.json -o #{$limitdir}/expected_limit_comparison --name-by=channel --legend-on-the-left --xrange=[110,140] --ref=llt"
end



#################################################################################
#### Copying card configuration to official place ###############################
#################################################################################
$httcombodir = "#{ENV['CMSSW_BASE']}/src/HiggsAnalysis/HiggsToTauTau/setup/vhtt/"
$auxdir      = "#{ENV['CMSSW_BASE']}/src/auxiliaries/datacards/collected/vhtt/"

def copy_file(source, target)
  file target => [source] do |t|
    sh "mkdir -p `dirname #{t.name}`"
    sh "cp -v #{t.prerequisites[0]} #{t.name}"
  end
  return target
end

def copy_configs(channel, vhtt_number)
  dir    = "#{$carddir}/#{channel}"
  htt_id = "sm-#{$period}-#{vhtt_number}"

  #copies cgs.conf
  copy_file("#{dir}/cgs.conf", "#{$httcombodir}/cgs-#{htt_id}.conf")

  #copies unc.conf
  copy_file("#{dir}/unc.conf", "#{$httcombodir}/unc-#{htt_id}.conf")

  #copies unc.vals
  copy_file("#{dir}/unc.vals", "#{$httcombodir}/unc-#{htt_id}.vals")

  return ["#{$httcombodir}/cgs-#{htt_id}.conf", "#{$httcombodir}/unc-#{htt_id}.conf", "#{$httcombodir}/unc-#{htt_id}.vals"]
end


mmt_cfg = copy_configs('mmt', '00')
emt_cfg = copy_configs('emt', '01')
eet_cfg = copy_configs('eet', '02')

file "#{$auxdir}/vhtt_llt.inputs-sm-#{$period}.root" => ["#{$carddir}/mmt/shapes.root",
                                                        "#{$carddir}/emt/shapes.root",
                                                        "#{$carddir}/eet/shapes.root"] do |t|
  sh "hadd -f #{t.name} #{t.prerequisites.join(' ')}"
end

task :copycards => ["#{$auxdir}/vhtt_llt.inputs-sm-#{$period}.root"] +
    mmt_cfg + emt_cfg + eet_cfg do |t|
    #puts t.investigation
end


#################################################################################
#### Background-only f3 pulls, to convince yourself and the others  #############
#### (but mostly the others) that the background estimation is fine #############
#################################################################################

$carddir = "results/#{$jobid}/bkg-only-pulls" #change global var so we can reuse the functions

mmt_f3_shape_file = "#{$mmtdir}/mmt_f3_shapes_#{$period}.root"
$categories_map['mmt'].each do |category|
  mmt_f3_shape_file = add_fake_errors(mmt_f3_shape_file, "mmt_f3", category)
end
task :mmt_f3_shapes => mmt_f3_shape_file

emt_f3_shape_file = "#{$emtdir}/emt_f3_shapes_#{$period}.root"
$categories_map['emt'].each do |category|
  emt_f3_shape_file = add_fake_errors(emt_f3_shape_file, "emt_f3", category)
end
task :emt_f3_shapes => emt_f3_shape_file

eet_f3_shape_file = "#{$eetdir}/eet_f3_shapes_#{$period}.root"
$categories_map['eet'].each do |category|
  eet_f3_shape_file = add_fake_errors(eet_f3_shape_file, "eet_f3", category)
end
task :eet_f3_shapes => eet_f3_shape_file

def make_copy_task(channel, shapefile)
  ret = "#{$carddir}/#{channel}/shapes.root"
  file ret => [shapefile] do |t|
    sh "mkdir -p `dirname #{t.name}`"
    sh "cp #{t.prerequisites[0]} #{t.name}"
  end
  return ret
end

task :mmt_copied_f3_shapes => copy_file(mmt_f3_shape_file, "#{$carddir}/mmt/shapes.root")
task :emt_copied_f3_shapes => copy_file(emt_f3_shape_file, "#{$carddir}/emt/shapes.root")
task :eet_copied_f3_shapes => copy_file(eet_f3_shape_file, "#{$carddir}/eet/shapes.root")

def make_f3_timestamp_task(cardmasses, channel)
  timestamp = "#{$carddir}/#{channel}/.creation_timestamp"
  #creates the tasks
  make_unc_conf_task(channel, '_f3')
  make_unc_vals_task(channel, '_f3')
  make_cgs_conf_task(channel)
  file timestamp => cardmasses.map{|x| make_datacard_task(x, channel)} do |t|
    sh "touch #{t.name}"
  end
end

file "#{$carddir}/llt/.creation_timestamp" => combine_channels(120) do |t|
  sh "touch #{t.name}"
end


task :f3_cards_mmt => make_f3_timestamp_task([120], 'mmt')
task :f3_cards_emt => make_f3_timestamp_task([120], 'emt')
task :f3_cards_eet => make_f3_timestamp_task([120], 'eet')
task :f3_cards_llt => "#{$carddir}/llt/.creation_timestamp"

task :f3_cards => [:f3_cards_mmt,
                :f3_cards_emt,
                :f3_cards_eet,
                :f3_cards_llt
               ]


def make_pulls_task(channel)
  pulls_timestamp = "#{$carddir}/#{channel}/.pulls_computed"
  carddir = $carddir #makes a copy so that if $cardir changes this does not
  file pulls_timestamp => "#{$carddir}/#{channel}/.creation_timestamp" do |t|
    chdir("#{carddir}/#{channel}") do
      sh "limit.py --max-likelihood --stable --rMin 0 --rMax 0 120"
      sh "python $CMSSW_BASE/src/HiggsAnalysis/CombinedLimit/test/diffNuisances.py 120/out/mlfit.root -f html > #{channel}.pulls.html"
      sh "python $CMSSW_BASE/src/HiggsAnalysis/CombinedLimit/test/diffNuisances.py 120/out/mlfit.root -a -f html > #{channel}.pulls.all.html"
      sh "python $CMSSW_BASE/src/HiggsAnalysis/CombinedLimit/test/diffNuisances.py 120/out/mlfit.root -a -f txt > #{channel}.pulls.all.raw_txt"
    end
    sh "touch #{t.name}"
  end
  return pulls_timestamp
end

task :f3_pulls_mmt => make_pulls_task('mmt')
task :f3_pulls_emt => make_pulls_task('emt')
task :f3_pulls_eet => make_pulls_task('eet')
task :f3_pulls_llt => make_pulls_task('llt')
task :f3_pulls => Array[:f3_pulls_mmt,
                        :f3_pulls_emt,
                        :f3_pulls_eet,
                        :f3_pulls_llt]

#################################################################################
#### Background-only f3 post-fit plots, to convince yourself and the       ######
#### others (but mostly the others) that the background estimation is fine ######
#################################################################################

def make_f3_postfit_shapes_task(channel)
  shape_file = "results/#{$jobid}/plots/#{channel}/f3/postfit/#{channel}_f3_postfit_shapes.root"
  carddir = $carddir #makes a copy so that if $cardir changes this does not
  file shape_file => "#{$carddir}/#{channel}/.pulls_computed" do |t|
    sh "mkdir -p `dirname #{t.name}`"
    sh "cp #{carddir}/#{channel}/shapes.root #{t.name}" #FIXME this may create to rake some problems if next command fails!
    sh "#{ENV['CMSSW_BASE']}/src/HiggsAnalysis/HiggsToTauTau/test/postfit.py  #{t.name} #{$carddir}/#{channel}/120/vhtt_#{channel}.txt --verbose --bins #{$categories_map[channel].join(' ')} --fitresults #{$carddir}/#{channel}/120/out/mlfit.txt"
  end
  return shape_file
end

task :f3_postfit_shapes_mmt => make_f3_postfit_shapes_task('mmt')
task :f3_postfit_shapes_emt => make_f3_postfit_shapes_task('emt')
task :f3_postfit_shapes_eet => make_f3_postfit_shapes_task('eet')
#task :f3_postfit_shapes_llt => make_f3_postfit_shapes_task('llt')
task :f3_postfit_shapes => Array[:f3_postfit_shapes_mmt,
                                 :f3_postfit_shapes_emt,
                                 :f3_postfit_shapes_eet]


#categories
$xlabels_map = Hash[
   'eet' => '"M_{e_{2}#tau} (GeV)"',
   'emt' => '"M_{l_{2}#tau} (GeV)"',
   'mmt' => '"M_{#mu_{2}#tau} (GeV)"',
]


def make_f3_postfit_plots_task(channel)
  resultdir  = "results/#{$jobid}/plots/#{channel}/f3/postfit"
  shape_file = "#{resultdir}/#{channel}_f3_postfit_shapes.root"
  plot_timestamp = "#{resultdir}/.postfit_plots_timestamp"
  file plot_timestamp => shape_file do |t|
    sh "mkdir -p `dirname #{t.name}`"
    $categories_map[channel].each do |category|
      sh "shapes2hist.py #{resultdir}/#{channel}_f3_postfit_shapes.root #{category} -e 'WH*' -o #{resultdir}/#{category}.png -x #{$xlabels_map[channel]}"
      sh "shapes2hist.py #{resultdir}/#{channel}_f3_postfit_shapes.root #{category} -e 'WH*' -o #{resultdir}/#{category}.pdf -x #{$xlabels_map[channel]}"
    end
    sh "shapes2hist.py #{resultdir}/#{channel}_f3_postfit_shapes.root #{$categories_map[channel].join(' ')} -e 'WH*' -o #{resultdir}/#{channel}_categories_summed.png -x #{$xlabels_map[channel]}"
    sh "touch #{t.name}"
  end
  return plot_timestamp
end

task :f3_postfit_plots_mmt => make_f3_postfit_plots_task('mmt')
task :f3_postfit_plots_emt => make_f3_postfit_plots_task('emt')
task :f3_postfit_plots_eet => make_f3_postfit_plots_task('eet')
#task :f3_postfit_plots_llt => make_f3_postfit_plots_task('llt')
task :f3_postfit_plots => Array[:f3_postfit_plots_mmt,
                                 :f3_postfit_plots_emt,
                                 :f3_postfit_plots_eet]
