# Get common recipes
recipes = ENV['fsa'] + '/PlotTools/rake/recipes.rake'
import recipes

$jobid = ENV['jobid']

# Figure out what run period we are in
$period = '8TeV'
#if $jobid.include? '8TeV'
#  $period = '8TeV'
#end


################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt").select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end

samples = Hash[
  "ewk" => Array['Zjets_M50', 
    'TTplusJets_madgraph'], 
  "ttbar" => Array['TTplusJets_madgraph'],
  "wjets" => get_sample_names('Wplus'),
  "zjets" => Array['Zjets_M50'],

   "signal" => get_sample_names('LFV'),
   "sm" => Array['VBF_H2Tau_M-125','GluGlu_H2Tau_M-125'],
  "data_mt" => get_sample_names("data_SingleMu") 
]

# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end

################################################################################
## Recipes to analyze LFV H->mutau
##  targets:
##     mt
################################################################################

task :mttight => get_analyzer_results("AnalyzeMuTauTight.py", samples['ewk'] + samples['wjets'] + samples['data_mt'] + samples['signal']+samples['sm'])

#task :testPy  => get_analyzer_results(  "AnalyzeMuTauTight.py",samples['signal'])

