# Get common recipes
recipes = ENV['fsa'] + '/PlotTools/rake/recipes.rake'
import recipes

$jobid = ENV['jobid']

# Figure out what run period we are in
$period = '8TeV'
PU = ENV['PU']
#if $jobid.include? '8TeV'
#  $period = '8TeV'
#end


################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt").select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end
#
samples = Hash[
  #"ewk" => Array['Zjets_M50'], 
   # 'TTplusJets_madgraph'], 
  #"ttbar" => Array['TTplusJets_madgraph'],
   "ttbar" => get_sample_names('TTJets'),
  "ttbar05" => get_sample_names('TTJets'),	
  "wjets" => get_sample_names('Wplus'),
  "wwjets" => get_sample_names('WWJets'),
  #"zjets" => Array['Zjets_M50'],
  "zjets" => get_sample_names('Zjets_M50'),

  "old_signal" => get_sample_names('H2Tau_M-126'),
  "new_signal" => get_sample_names('Minus'),	
  "sm" => Array['VBF_H2Tau_M-125'],
	#'GluGlu_H2Tau_M-125'], not working (July 1 2013)
  "data_mt" => get_sample_names('data_SingleMu'),
  "DY" => get_sample_names('DY'),
  "embedded" => get_sample_names('Embedded')

]

#samples = Hash[
  #"ewk" => Array[ 
  #'TTplusJets_madgraph'], 
  
#"ttbar" => get_sample_names('TTJets'),
 # "wjets" => get_sample_names('Wplus')
#  "wwjets" => get_sample_names('WWJets'),
#  "zjets" => Array['Zjets_M50'],

 # "old_signal" => get_sample_names('H2Tau_M-126'),
#  "new_signal" => get_sample_names('Minus'),   
#  "sm" => Array['VBF_H2Tau_M-125'],
        #'GluGlu_H2Tau_M-125'], not working (July 1 2013)
#  "data_mt" => get_sample_names("data_SingleMu") 
#]

# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end

################################################################################
## Recipes to analyze LFV H->mutau
##  targets:
##     mt
################################################################################

task :mttight => get_analyzer_results("AnalyzeMuTauTightvbfNew.py", samples['zjets'] + samples['wjets'] + samples['sm']+samples['new_signal'] + samples['data_mt'] + samples['ttbar'] + samples['wwjets'] + samples['DY'] + samples['embedded']
	)


##use $PU = false for samples with no pileup
task :pu1mttight  => get_analyzer_results(  "AnalyzeMuTauTightvbfNew.py",samples['old_signal'])
#Task for samples on login05
task :mttight05 => get_analyzer_results("AnalyzeMuTauTightvbf.py", samples['wjets'] + samples['ttbar05'])

